### ISSUE TITLE
Enable Encrypt sensitive information

### ISSUE THREAD

**Issue by micgruber** [oblakstudio/redisinsight#12]
When starting the first time I'm not able to select **Encrypt sensitive information**. Do I have to do any additional steps to make it work. Found no information in the docs. Deployed it in kubernetes with this config.

![config](https://github.com/oblakstudio/redisinsight/assets/19686895/7ba87549-bd93-497d-aa72-deeb3b2a9538)

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pv-claim
  namespace: namespace
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: namespace
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name:  redisinsight
          image: oblakstudio/redisinsight:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 5000
              protocol: TCP
---

**Comment by seebeen** [comment]
Hello,

Please read issue #2 .

Encrypting sensitive information shouldn't be important in the docker / kuberenets cluster, and by enabling encryption you actually reduce security because you need to run the app within container as root and container itself needs `IPC_LOCK` cap.
