### ISSUE TITLE
RIPROXYPATH is not working

### ISSUE THREAD

**Issue by anuragpathak21** [oblakstudio/redisinsight#4]
Setting environment variable RIPROXYENABLE = t and RIPROXYPATH = /redisinsight does not work. Redisinsight is still working on root path.

**Comment by seebeen** [comment]
Hello. I'll investigate this, and I'll try to squeeze it in the next release :)

**Comment by seebeen** [comment]
Hello, RIPROXYPATH is a feature of RedisInsight v1. For v2 you can place a frontend proxy like traefik or nginx and setup a path you want.
