### ISSUE TITLE
How To: Change server listening port

### ISSUE THREAD

**Issue by kurt-west** [oblakstudio/redisinsight#5]
Thank you so much for taking the time to build and maintain this container. 

I read that the listen port is fixed to 5000; however, looking at the [codebase](https://github.com/RedisInsight/RedisInsight/blob/cb71774bd1f18db7fdd14b954512932d60b26672/redisinsight/api/src/main.ts#L28) 5000 is the fallback port if `process.env.API_PORT` is not available.

I was able to successful get the server to directly listen on various ports by adding an env variable `API_PORT` set to the desired port number.

**Comment by seebeen** [comment]
It was fixed in an older version of the codebase. I'll update accordingly!

**Comment by kurt-west** [comment]
Thanks @seebeen, again thank you for your efforts maintaining this.

**Comment by seebeen** [comment]
Hola. We'll release a new version sometime next week with all of the updates pulled from upstream.

**Comment by seebeen** [comment]
Updates have been pushed. v2 branch is up on docker hub, and readme has been updated to reflect the changes.

**Comment by kurt-west** [comment]
Thank you again for your work on this.
