### ISSUE TITLE
Docker images are not updated propertly

### ISSUE THREAD

**Issue by germanattanasio** [oblakstudio/redisinsight#6]
The docker images are not being build because of a typescript error.
See:
<img width="1319" alt="ger-2023-10-04 at 14 06 16@2x" src="https://github.com/oblakstudio/redisinsight/assets/313157/feb66be6-6ead-431c-9fac-92ee7a26ea29">

**Comment by seebeen** [comment]
I'll czech. Thanks for notifying!

**Comment by seebeen** [comment]
Fixed :)
